Implement CI
* travis
* gitlab-ci

* trusty repo for puppet5
* fix error introduced by linting
* fix path of riemann.jar on Debian
* fix logfile quotes
* Fix final RC of smoke tests
* improve stdout of smoke tests
* drop support for puppet <4.9.0 (module data weren't collected before that)
* use bundle in smoke tests
* pdk requires Ruby version >= 2.1.9
* travis: use preinstalled ruby versions
* travis: add puppet version to output
* add debug info to ci

diff --git a/smoke/test b/smoke/test
--- a/smoke/test
+++ b/smoke/test
@@ -1,20 +1,34 @@
-#!/bin/sh -eu
+#!/bin/sh -u
 
 [ ! -d "./smoke" ] && { echo "No tests to run"; exit 0; }
 
+should_succeed()
+{
+	$@
+	rc=$?
+	case $rc in
+		0|2) echo '* Passed OK with RC' $rc;;
+		*) echo '* Should have passed but Failed with RC' $rc
+			 exit $rc;;
+	esac
+}
+
+should_fail()
+{
+	$@
+	rc=$?
+	case $rc in
+		0|2) echo '* Should have Failed but passed with RC' $rc
+			   exit 8;;
+		*) echo '* Failed OK with RC ' $rc;;
+	esac
+}
+
 for manifest in $(find ./smoke -type f -name 'OK_*.pp'); do
-	echo '*'
-	echo '* Testing manifest `'$manifest'`'
-	echo '*'
- 	puppet apply $manifest
-	echo '*'
-	echo '* Passed OK *'
+	echo -n '* Testing manifest `'$manifest'`'
+ 	should_succeed bundle exec puppet apply --logdest /dev/null --detailed-exitcodes $manifest
 done
 for manifest in $(find ./smoke -type f -name 'NOK_*.pp'); do
-	echo '*'
-	echo '* Testing manifest `'$manifest'`'
-	echo '*'
- 	! puppet apply $manifest
-	echo '*'
-	echo '* Failed OK *'
+	echo -n '* Testing manifest `'$manifest'`'
+ 	should_fail bundle exec puppet apply --logdest /dev/null --detailed-exitcodes $manifest
 done
